<?php

/**
 * @file
 * Contains client.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function client_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the client module.
    case 'help.page.client':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('whatever') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function client_theme() {
  $theme = [];

  return $theme;
}
