<?php

/**
 * @file
 * .module file for all of the hooks that christian module implements.
 */

use Drupal\Core\Routing\RouteMatchInterface;


function christian_permissions()
{
    $permissions = array(
        'view christian' => array(
            'title' => t('View christian module'),
            'description' => t('Permissions to view the christian module'),
        )
    );
    return $permissions;
}

/**
 * Implements hook_theme()
 */
function christian_theme()
{
    return array(
        'christian_header' => array(
            'theme' => 'christian_header',
            'variables' => array(
                'items' => array(),
            ),
        ),
        'christian_carousel' => array(
            'theme' => 'christian_carousel',
            'variables' => array(
                'items' => array(),
            ),
        ),
        'christian_contact' => array(
            'theme' => 'christian_contact',
            'variables' => array(
                'items' => array(),
            ),
        ),
        'christian_murer_teaser' => array(
            'theme' => 'christian_murer_teaser',
            'variables' => array(
                'items' => array()
            ),
        ),
        'christian_vinduespudsning_teaser' => array(
            'theme' => 'christian_vinduespudsning_teaser',
            'variables' => array(
                'items' => array(),
            ),
        ),
        'christian_murer' => array(
            'theme' => 'christian_murer',
            'variables' => array(
                'items' => array(),
            ),
        ),
        'christian_vinduespudsning' => array(
            'theme' => 'christian_vinduespudsning',
            'variables' => array(
                'items' => array(),
            ),
        ),
        'christian_footer' => array(
            'theme' => 'christian_footer',
            'variables' => array(
              'items' => array(),
            ),
        ),
        'christian_contact_teaser' => array(
            'theme' => 'christian_contact_teaser',
            'variables' => array(
                'items' => array(),
            )
        ),
    );
}

function christian_preprocess_region(&$variables)
{
    $region = $variables['elements']['#region'];
    if ($region === 'content') {
        $variables['attributes']['class'][] = 'container';
        $variables['attributes']['class'][] = 'marketing';
    } else if($region === 'featured_top') {
        $variables['attributes']['class'][] = 'container';
        $variables['attributes']['class'][] = 'marketing';
    } else if($region === 'footer_first') {
        $variables['attributes']['class'][] = 'container';
    }
}

/**
 * @param $variables
 */
function template_preprocess_christian_carousel(&$variables)
{
    global $base_root, $base_path;
    $image1 = 'imageone.jpg';
    $image2 = 'imagetwo.jpg';
    $image3 = 'imagethree.jpg';

    $variables['image1'] = $base_root . $base_path . drupal_get_path('module', 'christian') . '/images/' . $image1;
    $variables['image2'] = $base_root . $base_path . drupal_get_path('module', 'christian') . '/images/' . $image2;
    $variables['image3'] = $base_root . $base_path . drupal_get_path('module', 'christian') . '/images/' . $image3;
}

/**
 * @param $variables
 */
function template_preprocess_christian_murer(&$variables)
{
    global $base_root, $base_path;
    $image = 'toilet.jpg';
    $variables['image'] = $base_root . $base_path . drupal_get_path('module', 'christian') . '/images/' . $image;
}

function template_preprocess_christian_vinduespudsning(&$variables) {
    global $base_root, $base_path;
    $image = 'cleaning.jpg';
    $variables['image'] = $base_root . $base_path . drupal_get_path('module', 'christian') . '/images/' . $image;
}

function template_preprocess_christian_murer_teaser(&$variables) {
    global $base_root, $base_path;
    $image = 'constructionworker.jpg';
    $variables['image'] = $base_root . $base_path . drupal_get_path('module', 'christian') . '/images/' . $image;
}

function template_preprocess_christian_vinduespudsning_teaser(&$variables) {
    global $base_root, $base_path;
    $image = 'windowcleaner.jpg';
    $variables['image'] = $base_root . $base_path . drupal_get_path('module', 'christian') . '/images/' . $image;
}

function template_preprocess_christian_contact_teaser(&$variables) {
    global $base_root, $base_path;
    $image = 'christian.jpg';
    $variables['image'] = $base_root . $base_path . drupal_get_path('module', 'christian') . '/images/' . $image;
}

/**function template_preprocess_christian_contact(&$variables) {
    global $base_root, $base_path;
    $image = 'christian.jpg';
    $variables['image'] = $base_root . $base_path . drupal_get_path('module', 'christian') . '/images/' . $image;
}*/
