<?php

/**
 * @file
 * Contains contact.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function contact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the contact module.
    case 'help.page.contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function contact_theme() {
  $theme = [];

  return $theme;
}
